gen_uuid.c: s/_SVID_SOURCE/_DEFAULT_SOURCE/
In file included from /usr/include/unistd.h:25:0,
                 from libuuid_unix/gen_uuid.c:42:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and
_SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use
_DEFAULT_SOURCE"

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>